### ISSUE TITLE
Use specific version in examples/docker.sh

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/cluster#54]
Let's pick up the version number of the cluster docker image from cluster.ini.

https://github.com/liquidinvestigations/cluster/blob/68b652bd561bfd66611a9ab7d4f625eff56048d8/examples/docker.sh#L5

**Comment by gabriel-v** [comment]
You want to parse the ini file in this bash script? Or do you want to switch this script to Python and re-enter the complicated land of installing dependencies?

Let's just cut'n'paste another argument... `--image` or something

**Comment by salevajo** [comment]
That’s fine for me, too

**Comment by salevajo** [comment]
And the default is just :latest

**Comment by mgax** [comment]
`--image` is fine, but i'd feel better if that version was enshrined in a configuration file, otherwise i'd have to run docker introspection commands to figure out what version should be running. Maybe using this horrible one-liner? :) https://stackoverflow.com/a/40778047

**Comment by gabriel-v** [comment]
> https://stackoverflow.com/a/40778047

NOPE

**Comment by salevajo** [comment]
docker ps is showing the version - that's already a good one-liner to get the info:
```
inv@hoover-inv:/opt/cluster$ docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS
                                                     NAMES
7623cfcda0ab        liquidinvestigations/cluster:0.2.0                    "/opt/cluster/docker…"   About an hour ago   Up About an hour
                                                     cluster
```

**Comment by gabriel-v** [comment]
We should also rename the script, since it's not an example anymore...

I just can't find a better name right now.

**Comment by salevajo** [comment]
We can move into clusters bin dir
