### ISSUE TITLE
Improve Nomad logging to get stdout/stderr for finished allocations

### ISSUE THREAD

**Issue by salevajo** [liquidinvestigations/cluster#69]
Currently it's only possible to access logs from running allocations within Nomad. Sometimes, esp. when restarting services in a faulty situation it would be better to get logs from the crashed allocation to analyse while users can already access the restarted service.

**Comment by gabriel-v** [comment]
The logs can be found on `$IP:9990/grafana`, select `Loki` as a data source and type in a query.
