### ISSUE TITLE
Document or set higher sysctl inotify limits

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/cluster#90]
When running a lot of containers per node, we really want to set these:

```
fs.inotify.max_queued_events = 524288
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches = 8192
```

This is because `dockerd` and `promtail` will open a `tail -f` for each container, so we end up with errors that say `failed to create inotify: No file descriptors available`

**Comment by gabriel-v** [comment]
@mgax How about we run `sysctl` in the docker entrypoint and forget about them?

**Comment by mgax** [comment]
> How about we run `sysctl` in the docker entrypoint and forget about them?

Fine by me. It would be nice to add a comment explaining why, and what are default values on typical systems. Perhaps make them configurable.

**Comment by gabriel-v** [comment]
not needed
