### ISSUE TITLE
Dashboard not found

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/cluster#93]
After upgrading to the latest cluster image, a few new dashboards show up in the menu, but they throw a bunch of "404 not found" errors:

<img width="1182" alt="Screenshot 2019-10-14 at 11 22 02" src="https://user-images.githubusercontent.com/27617/66737539-f37a3400-ee74-11e9-829b-22382962dfad.png">

Also, I'm pretty sure none of my machines are called `trashcan` :))

https://github.com/liquidinvestigations/cluster/blob/081e839e507bf85427ea2d37a7d94fab5dd20efd/grafana-dashboards/telegraf-system.json#L4741-L4749

**Comment by gabriel-v** [comment]
it works if the server is up and you refresh. The server was not up in your photo.
